language: node_js
node_js:
  - "5"
  - "4"
  - "4.0"

after_success: 'npm run coverage'

deploy:
  provider: npm
  email: jaroslav.kubicek@gmail.com
  api_key:
    secure: GS7HhDoDSI3oh7CMmekXAr8LtVSlQNpT/z50RuAxt4AO8YE8h9uL2jOwmPR+nCk5NXF+wZFF9KPW5fddv9NzTix/IRCgVmiNI80ZCTDU18IqnkM+T+ExC1LvMJME7pYkDduE4Wk/1vhPe4CI4meiX+CViiEG9x5GBs1eBCqdto/EqV7YreBGtsyR0+ju5VxitJ8SlTcQ0BCD6/Xcr5u1APfrHl0GMY1NogvuNIwXPD9rdk2mBT5M+w9vXeD3wkGTdmmR+/7ZrjPh8qdnGCqxNVwQURRgTnh+WlsyJcfkDVU6FWwRaN8xINavZmcrYMWy2KqhxYzCt9OVCWwZWvTzDyoTY6NnjBAq4hPB/Le3E6tD4gOUy3wNBjcpgB3fylHlwcIgZhoONZx8btktdpcdN4BtBvaUC5APyXUT1YDDF2WeYwtzIuUVbakyIza3lE42/qizHy99UiwskfrCOvPg0isBc9kAoWNVvoVP1EJ6JzvKuC0xIo0y86XClfFR9SjFXzz/75PUMg6zPsIytRbmTJepZljfp9TSOKV6mSWZ7qnwn1Lr6uj/EiTp7s6yCTdhEjc4lMu7B9Jh9lu2J+5pih840BABHWivKtEyvJlBYR4vclNiA/iwOx/yG275wVThYgncefMkEKivHYSZjVZcLIDeBEt3wDLvtl87LztkCHs=
  on:
    tags: true
