language: node_js
node_js:
- '5'
- '4'
- '4.0'
after_success: npm run coverage
deploy:
  provider: npm
  email: jaroslav.kubicek@gmail.com
  api_key:
    secure: TWgKo+5jFp5tnmuFKrx6fVnnXce557nbv//rIK5juUML9Q7RdP2I+BYOzIcklt5fWmpdgwLORFXrkL3qUys9gtQ7LzjAFG1ikljU3sE/lQlLxMy7dUQT1R1FbjMtwPhMnIO1qK/e7taHxSdm9ynvbz8S6lgjpeOdupFcUe6e7YoLI+NPx+aivb8nxdJowb5oxSGuceqvuYa4p8wGbrAosZtIia7zjxoPmPekBEQ6eVXpEB5/qgLfKsmFZYEaBusL+ZZC7uvr0K8iepjRciVAZtm4lAEtOi1JY4VV0dsK+3fOMIKczIflFwixQfi8P+/SZLQlqSsGw9GQ+0qpKs5Sr4a4DP6b5zrPkqNybYqFif+MjfQo0ZzdZ7Dz+pHJsy50zfAX//HghhHIeBlb6ZopK/MCwMaB5cMgmwWJZXu9ui+DAAMPj9DZ5VZooOLNOZ3UWP/3A6pweZtmAPljs/DKuJF5WHXCGywRXyzW8zscwdWv0osQeuT4eKtkEpcdvs+tHOIWYeTc0u6LEGXDit2Wjb55iMd+AMis3oQC0qt5Cd3ifw+dJ7acnd2dRH1US8uBAv+aBn/0W6aeR2v64SqcQ2HLDZXGQU2ep2dwdtJDtAqb5UTsyhwjzWk1oiuDNvrC9nJN4/P8cP2yqUV4Irhk5SvQFY4HCiNZpEcGfst0SrI=
  on:
    tags: true
    repo: jaroslav-kubicek/spawn-generator
